version: '3.0'
services:
  db:
    container_name: db-worganizer
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5436:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
